#ifndef CONFIG_H
#define CONFIG_H

//constanes 


#define LARGO_MAXIMO_CARACTERES 256
#define ARCHIVO_USUARIO "data/usuario.txt"
#define DESPLAZAMIENTO_CIFRADO 4
#define ACCESO_CORRECTO 0
#define PASSWORD_INCORRECTA 1
#define USUARIO_INCORRECTO 2


#define USUARIO_Y_PASSWORD_LEIDOS 2

#define OPERACION_FALLIDA -1
#define OPERACION_EXITOSA 0



#endif //CONFIG_H